// ─── Mission Service ───
// Місії: щоденні, тижневі, сюжетні, досягнення

import {
  doc, getDoc, getDocs, addDoc, updateDoc,
  collection, query, where, onSnapshot,
  runTransaction, serverTimestamp, writeBatch,
} from 'firebase/firestore'
import { db } from './config'
import { addResearchPoints } from './scienceService'

// ─── Константи ───────────────────────────────────────────────

export const MISSION_TYPES = {
  daily:       { name: 'Щоденна',    icon: '📅', color: '#00ff88' },
  weekly:      { name: 'Тижнева',    icon: '📆', color: '#ffd700' },
  story:       { name: 'Сюжетна',    icon: '📖', color: '#ff4500' },
  achievement: { name: 'Досягнення', icon: '🏆', color: '#b9f2ff' },
}

// ─── Дефолтні місії (генеруються для всіх) ───────────────────

export const DEFAULT_DAILY_MISSIONS = [
  {
    id: 'daily_collect_resources',
    title: 'Збирач',
    description: 'Зібрати ресурси з будь-якої копальні',
    flavorText: '«Надра ще зберігають скарби старого світу. Копальня — твій ключ до них.»',
    type: 'daily',
    objective: { action: 'collect_mine', count: 1 },
    reward: { gold: 50 },
    xpReward: 5,
  },
  {
    id: 'daily_upgrade_building',
    title: 'Будівельник',
    description: 'Покращити будь-яку будівлю',
    flavorText: '«Кожна нова будівля — доказ того, що руїни можна перетворити на місто.»',
    type: 'daily',
    objective: { action: 'upgrade_building', count: 1 },
    reward: { gold: 80, bits: 10 },
    xpReward: 10,
  },
  {
    id: 'daily_complete_task',
    title: 'Студент',
    description: 'Виконати будь-яке завдання',
    flavorText: '«Знання — єдина зброя, яка не ржавіє. Nova Academy це пам\'ятає.»',
    type: 'daily',
    objective: { action: 'complete_task', count: 1 },
    reward: { gold: 100, bits: 20 },
    xpReward: 15,
  },
  {
    id: 'daily_trade',
    title: 'Торговець',
    description: 'Здійснити торгову операцію',
    flavorText: '«Торгівля після Колапсу — це довіра. Кожна угода відновлює зв\'язки між таборами.»',
    type: 'daily',
    objective: { action: 'trade', count: 1 },
    reward: { gold: 60 },
    xpReward: 5,
  },
  {
    id: 'daily_research',
    title: 'Дослідник',
    description: 'Запустити дослідження клітинки',
    flavorText: '«Карта руїн не повна. Кожна розвідана клітинка — крок до розуміння катастрофи 2039.»',
    type: 'daily',
    objective: { action: 'start_research', count: 1 },
    reward: { bits: 30 },
    xpReward: 5,
  },
  {
    id: 'daily_place_workers',
    title: 'Менеджер',
    description: 'Розмістити 3 робітників',
    flavorText: '«Без праці немає прогресу. Академія живе зусиллями кожного студента.»',
    type: 'daily',
    objective: { action: 'place_workers', count: 3 },
    reward: { gold: 40 },
    xpReward: 5,
  },
  {
    id: 'daily_field_expedition',
    title: 'Першовідкривач',
    description: 'Відправ команду на будь-яке поле',
    flavorText: '«Зовні стін — невідомість. Але тільки ті, хто виходить назовні, знають, що там насправді.»',
    type: 'daily',
    objective: { action: 'start_expedition', count: 1 },
    reward: { energy: 30, gold: 50 },
    xpReward: 10,
    rpReward: 2,
  },
  {
    id: 'daily_extract_field',
    title: 'Видобувач',
    description: 'Видобудь ресурси з ресурсного поля',
    flavorText: '«Земля ще не спустошена. Правильні руки і правильні інструменти — і вона віддасть усе.»',
    type: 'daily',
    objective: { action: 'claim_extract', count: 1 },
    reward: { bio: 30, energy: 20 },
    xpReward: 12,
    rpReward: 3,
  },
  {
    id: 'daily_field_ruin',
    title: 'Штурмовик',
    description: 'Штурмуй руїну через поле',
    flavorText: '«Руїни — не просто уламки. Там схована технологія, яка може врятувати або знищити.»',
    type: 'daily',
    objective: { action: 'claim_attack', count: 1 },
    reward: { gold: 120, code: 20 },
    xpReward: 15,
    rpReward: 3,
  },
]

export const DEFAULT_WEEKLY_MISSIONS = [
  {
    id: 'weekly_5_tasks',
    title: 'Відмінник',
    description: 'Виконати 5 завдань за тиждень',
    type: 'weekly',
    objective: { action: 'complete_task', count: 5 },
    reward: { gold: 500, bits: 100, code: 30 },
    xpReward: 50,
    diamondReward: 1,
  },
  {
    id: 'weekly_3_trades',
    title: 'Підприємець',
    description: 'Здійснити 3 торгові операції',
    type: 'weekly',
    objective: { action: 'trade', count: 3 },
    reward: { gold: 300, crystals: 10 },
    xpReward: 30,
  },
  {
    id: 'weekly_ruin_clear',
    title: 'Мисливець на руїни',
    description: 'Зачистити 2 руїни',
    type: 'weekly',
    objective: { action: 'clear_ruin', count: 2 },
    reward: { gold: 400, bits: 80, code: 20 },
    xpReward: 40,
    diamondReward: 1,
  },
  {
    id: 'weekly_upgrade_3',
    title: 'Архітектор тижня',
    description: 'Покращити 3 будівлі',
    type: 'weekly',
    objective: { action: 'upgrade_building', count: 3 },
    reward: { gold: 350, stone: 50 },
    xpReward: 30,
  },
  {
    id: 'weekly_collect_500',
    title: 'Шахтар',
    description: 'Зібрати 500 одиниць ресурсів з копалень',
    type: 'weekly',
    objective: { action: 'collect_total', count: 500 },
    reward: { gold: 300, crystals: 15 },
    xpReward: 35,
  },
  {
    id: 'weekly_recruit_units',
    title: 'Командир',
    description: 'Найняти 3 юніти',
    type: 'weekly',
    objective: { action: 'recruit_unit', count: 3 },
    reward: { gold: 250, bits: 50 },
    xpReward: 25,
  },
  {
    id: 'weekly_field_expeditions',
    title: 'Дослідник полів',
    description: 'Відправ 5 місій на поля',
    type: 'weekly',
    objective: { action: 'start_expedition', count: 5 },
    reward: { gold: 400, energy: 80, bits: 60 },
    xpReward: 50,
    rpReward: 8,
  },
  {
    id: 'weekly_field_extractions',
    title: 'Промисловець',
    description: 'Видобудь ресурси з 3 різних полів',
    type: 'weekly',
    objective: { action: 'claim_extract', count: 3 },
    reward: { gold: 350, bio: 60, crystals: 20 },
    xpReward: 40,
    rpReward: 6,
  },
]

export const DEFAULT_STORY_MISSIONS = [
  // ─── Глава 0: Нульовий день ───────────────────────────────
  {
    id: 'story_0_1',
    title: 'Пробудження',
    description: 'Ти відкриваєш очі. Навколо — стіни бункера. Nova Academy чекає.',
    type: 'story',
    chapter: 0,
    order: 1,
    chapterName: 'Нульовий день',
    objective: { action: 'upgrade_castle', targetLevel: 1, count: 1 },
    reward: { gold: 50 },
    xpReward: 20,
    nextMission: 'story_0_2',
    loreText: 'Перший крок зроблено. Замок ожив — тепер це твій дім серед руїн.',
  },
  {
    id: 'story_0_2',
    title: 'Перша будівля',
    description: 'Відновити сервер — базова умова виживання в новому світі.',
    type: 'story',
    chapter: 0,
    order: 2,
    chapterName: 'Нульовий день',
    objective: { action: 'upgrade_building', target: 'server', targetLevel: 1, count: 1 },
    reward: { gold: 75, bits: 10 },
    xpReward: 20,
    nextMission: 'story_0_3',
    requires: 'story_0_1',
    loreText: 'Сервер гуде вперше за роки. Дані течуть — уривки старого світу повертаються.',
  },
  {
    id: 'story_0_3',
    title: 'Перші дослідження',
    description: 'Вивчи територію навколо бункера. Знання — це виживання.',
    type: 'story',
    chapter: 0,
    order: 3,
    chapterName: 'Нульовий день',
    objective: { action: 'start_research', count: 1 },
    reward: { bits: 20 },
    xpReward: 15,
    nextMission: 'story_0_4',
    requires: 'story_0_2',
    loreText: 'Перша клітинка досліджена. Карта руїн починає набувати форми.',
  },
  {
    id: 'story_0_4',
    title: 'Шлях вперед',
    description: 'Збудуй лабораторію — наука є основою виживання в новому світі.',
    type: 'story',
    chapter: 0,
    order: 4,
    chapterName: 'Нульовий день',
    objective: { action: 'upgrade_building', target: 'lab', targetLevel: 1, count: 1 },
    reward: { gold: 50, bits: 15 },
    xpReward: 10,
    nextMission: 'story_0_5',
    requires: 'story_0_3',
    loreText: 'Лабораторія збудована. Наука повертається. Nova Academy готова приймати нових студентів.',
  },
  {
    id: 'story_0_5',
    title: 'Перший захисник',
    description: 'Найми першого юніта. Nova Academy потребує захисників.',
    type: 'story',
    chapter: 0,
    order: 5,
    chapterName: 'Нульовий день',
    objective: { action: 'recruit_unit', count: 1 },
    reward: { gold: 100, bits: 20 },
    xpReward: 15,
    nextMission: 'story_1_1',
    requires: 'story_0_4',
    loreText: 'Перший захисник стоїть на варті. Академія більше не беззахисна.',
  },

  // ─── Глава 1: Початок ─────────────────────────────────────
  {
    id: 'story_1_1',
    title: 'Пробудження',
    description: 'Ти прокидаєшся в бункері. Навколо — руїни старого світу. Час відбудовувати.',
    type: 'story',
    chapter: 1,
    order: 1,
    objective: { action: 'upgrade_building', target: 'server', targetLevel: 1, count: 1 },
    reward: { gold: 100 },
    xpReward: 10,
    nextMission: 'story_1_2',
    loreText: 'Стародавній сервер гуде, оживаючи вперше за десятиліття. Дані починають текти — залишки знань минулого.',
  },
  {
    id: 'story_1_2',
    title: 'Перші ресурси',
    description: 'Дослідж територію навколо бункера. Знайди поклади ресурсів.',
    type: 'story',
    chapter: 1,
    order: 2,
    objective: { action: 'start_research', count: 1 },
    reward: { gold: 150, bits: 30 },
    xpReward: 15,
    nextMission: 'story_1_3',
    requires: 'story_1_1',
    loreText: 'Сканер показує слабкі сигнали під землею. Щось там є — потрібна лабораторія для аналізу.',
  },
  {
    id: 'story_1_3',
    title: 'Лабораторія',
    description: 'Збудуй лабораторію для аналізу зразків.',
    type: 'story',
    chapter: 1,
    order: 3,
    objective: { action: 'upgrade_building', target: 'lab', targetLevel: 1, count: 1 },
    reward: { gold: 200, bits: 50 },
    xpReward: 20,
    nextMission: 'story_1_4',
    requires: 'story_1_2',
    loreText: 'Лабораторія оживає. Тепер ти можеш аналізувати поклади і будувати копальні. Це змінює все.',
  },
  {
    id: 'story_1_4',
    title: 'Перша копальня',
    description: 'Побудуй свою першу копальню на розкритому покладі.',
    type: 'story',
    chapter: 1,
    order: 4,
    objective: { action: 'build_mine', count: 1 },
    reward: { gold: 200, bits: 40, code: 10 },
    xpReward: 20,
    nextMission: 'story_1_5',
    requires: 'story_1_3',
    loreText: 'Бур входить у землю. Перші кристали блищать. Цивілізація повертається — крок за кроком.',
  },
  {
    id: 'story_1_5',
    title: 'Комунікація',
    description: 'Збудуй Вежу зв\'язку і зв\'яжись з іншими поселеннями.',
    type: 'story',
    chapter: 1,
    order: 5,
    objective: { action: 'upgrade_building', target: 'tower', targetLevel: 1, count: 1 },
    reward: { gold: 250, code: 20 },
    xpReward: 25,
    nextMission: 'story_2_1',
    requires: 'story_1_4',
    loreText: 'Вежа випромінює сигнал. Через хвилину — відповідь. Ти не один. На карті з\'являються інші поселення.',
  },

  // ─── Глава 2: Розвиток ────────────────────────────────────
  {
    id: 'story_2_1',
    title: 'Торгові шляхи',
    description: 'Здійсни свою першу торгову операцію з іншим гравцем.',
    type: 'story',
    chapter: 2,
    order: 1,
    objective: { action: 'trade', count: 1 },
    reward: { gold: 300, crystals: 5 },
    xpReward: 20,
    nextMission: 'story_2_2',
    requires: 'story_1_5',
    loreText: 'Каравани знову рухаються дорогами. Торгівля — кров нової цивілізації.',
  },
  {
    id: 'story_2_2',
    title: 'Укріплення',
    description: 'Покращи замок до 2 рівня. Твоє поселення росте.',
    type: 'story',
    chapter: 2,
    order: 2,
    objective: { action: 'upgrade_castle', targetLevel: 2, count: 1 },
    reward: { gold: 400, stone: 100 },
    xpReward: 30,
    nextMission: 'story_2_3',
    requires: 'story_2_1',
    loreText: 'Стіни стають вищими. Тепер це не просто бункер — це дім.',
  },
  {
    id: 'story_2_3',
    title: 'Перший солдат',
    description: 'Найми свого першого юніта-робота.',
    type: 'story',
    chapter: 2,
    order: 3,
    objective: { action: 'recruit_unit', count: 1 },
    reward: { gold: 300, bits: 50 },
    xpReward: 25,
    nextMission: 'story_2_4',
    requires: 'story_2_2',
    loreText: 'Механічний воїн активується. Його червоні очі спалахують. "Протокол захисту — активовано."',
  },
  {
    id: 'story_2_4',
    title: 'Розвідка руїн',
    description: 'Атакуй руїну тіру 1 і здобудь ресурси.',
    type: 'story',
    chapter: 2,
    order: 4,
    objective: { action: 'clear_ruin', tier: 1, count: 1 },
    reward: { gold: 500, bits: 100, code: 30 },
    xpReward: 40,
    diamondReward: 1,
    nextMission: 'story_3_1',
    requires: 'story_2_3',
    loreText: 'Склад зачищено. Серед уламків — старі технології, які ще можна відновити. І записка: "Генезис чекає."',
  },

  // ─── Глава 3: Наука ───────────────────────────────────────
  {
    id: 'story_3_1',
    title: 'Нова ера',
    description: 'Збудуй Теплицю і почни вивчати природничі науки.',
    type: 'story',
    chapter: 3,
    order: 1,
    objective: { action: 'upgrade_building', target: 'greenhouse', targetLevel: 1, count: 1 },
    reward: { gold: 400, bio: 30 },
    xpReward: 30,
    nextMission: 'story_3_2',
    requires: 'story_2_4',
    loreText: 'Перші паростки пробиваються крізь бетон. Життя повертається.',
  },
  {
    id: 'story_3_2',
    title: 'Енергія майбутнього',
    description: 'Збудуй Реактор або Сонячну батарею.',
    type: 'story',
    chapter: 3,
    order: 2,
    objective: { action: 'upgrade_building', target: ['reactor', 'solar_array'], targetLevel: 1, count: 1 },
    reward: { gold: 400, energy: 30 },
    xpReward: 30,
    nextMission: 'story_3_3',
    requires: 'story_3_1',
    loreText: 'Реактор гуде. Або сонячні панелі блищать. Енергія тече — і з нею приходять нові можливості.',
  },
  {
    id: 'story_3_3',
    title: 'Генезис',
    description: 'Атакуй Зруйновану лабораторію "Генезис" (тір 2).',
    type: 'story',
    chapter: 3,
    order: 3,
    objective: { action: 'clear_ruin', tier: 2, count: 1 },
    reward: { gold: 800, bits: 200, bio: 50, energy: 50 },
    xpReward: 60,
    diamondReward: 2,
    nextMission: 'story_4_1',
    requires: 'story_3_2',
    loreText: 'Прототипи серії GN деактивовано. У серці лабораторії — креслення "Протоколу Відродження". Частина перша з трьох.',
  },

  // ─── Глава 4: Фінал бети ──────────────────────────────────
  {
    id: 'story_4_1',
    title: 'Бункер Старого Світу',
    description: 'Підготуй армію і штурмуй Бункер Старого Світу (тір 3).',
    type: 'story',
    chapter: 4,
    order: 1,
    objective: { action: 'clear_ruin', tier: 3, count: 1 },
    reward: { gold: 1500, bits: 500, code: 200, crystals: 100, bio: 100, energy: 100 },
    xpReward: 100,
    diamondReward: 5,
    nextMission: null,
    requires: 'story_3_3',
    loreText: 'Масивні двері відчиняються. Всередині — Протокол Відродження. Повний. Ти тримаєш в руках ключ до відновлення цивілізації. Але це лише початок...',
  },

  // ─── Глава 5: Захист ──────────────────────────────────────
  {
    id: 'story_5_1',
    title: 'Зміцнення стін',
    description: 'Апгрейд замку — базова потреба для розширення Академії.',
    type: 'story',
    chapter: 5,
    order: 1,
    chapterName: 'Захист',
    objective: { action: 'upgrade_castle', targetLevel: 2, count: 1 },
    reward: { gold: 400, stone: 80 },
    xpReward: 30,
    nextMission: 'story_5_2',
    requires: 'story_4_1',
    loreText: 'Мури стали вищими. Тепер Академія може прийняти більше людей.',
  },
  {
    id: 'story_5_2',
    title: 'Вежа повідомлень',
    description: 'Вежа зв\'язку другого рівня розширює радіус сигналу.',
    type: 'story',
    chapter: 5,
    order: 2,
    chapterName: 'Захист',
    objective: { action: 'upgrade_building', target: 'tower', targetLevel: 2, count: 1 },
    reward: { gold: 350, code: 30 },
    xpReward: 35,
    nextMission: 'story_5_3',
    requires: 'story_5_1',
    loreText: 'Сигнал досягає далеких поселень. Союзники відповідають — ти не один.',
  },
  {
    id: 'story_5_3',
    title: 'Гарнізон',
    description: 'Три юніти — мінімальний гарнізон для захисту периметру.',
    type: 'story',
    chapter: 5,
    order: 3,
    chapterName: 'Захист',
    objective: { action: 'recruit_unit', count: 3 },
    reward: { gold: 300, bits: 60 },
    xpReward: 35,
    nextMission: 'story_5_4',
    requires: 'story_5_2',
    loreText: 'Три захисники на варті. Периметр тримається. Академія може спати спокійно.',
  },
  {
    id: 'story_5_4',
    title: 'Зачистка сектору',
    description: 'Очисти руїну тір 1 для розширення безпечної зони.',
    type: 'story',
    chapter: 5,
    order: 4,
    chapterName: 'Захист',
    objective: { action: 'clear_ruin', tier: 1, count: 1 },
    reward: { gold: 500, bits: 100 },
    xpReward: 40,
    nextMission: 'story_5_5',
    requires: 'story_5_3',
    loreText: 'Сектор зачищено. На карті з\'являється нова безпечна зона.',
  },
  {
    id: 'story_5_5',
    title: 'Цитадель',
    description: 'Замок третього рівня — символ стабільності нового світу.',
    type: 'story',
    chapter: 5,
    order: 5,
    chapterName: 'Захист',
    objective: { action: 'upgrade_castle', targetLevel: 3, count: 1 },
    reward: { gold: 600, stone: 150, crystals: 20 },
    xpReward: 50,
    nextMission: 'story_6_1',
    requires: 'story_5_4',
    loreText: 'Цитадель піднімається над руїнами. Вперше за роки — справжнє місто.',
  },

  // ─── Глава 6: Ресурси ─────────────────────────────────────
  {
    id: 'story_6_1',
    title: 'Надра землі',
    description: 'Збудуй першу копальню для видобутку ресурсів.',
    type: 'story',
    chapter: 6,
    order: 1,
    chapterName: 'Ресурси',
    objective: { action: 'build_mine', count: 1 },
    reward: { gold: 250, bits: 40 },
    xpReward: 30,
    nextMission: 'story_6_2',
    requires: 'story_5_5',
    loreText: 'Перша шахта відкрита. Земля ще зберігає скарби, яких не знищив Колапс.',
  },
  {
    id: 'story_6_2',
    title: 'Розширення шахти',
    description: 'Покращ копальню до другого рівня для збільшення видобутку.',
    type: 'story',
    chapter: 6,
    order: 2,
    chapterName: 'Ресурси',
    objective: { action: 'upgrade_building', target: 'mine', targetLevel: 2, count: 1 },
    reward: { gold: 350, bits: 60 },
    xpReward: 35,
    nextMission: 'story_6_3',
    requires: 'story_6_1',
    loreText: 'Глибші тунелі — більше ресурсів. Академія починає накопичувати запаси.',
  },
  {
    id: 'story_6_3',
    title: 'Зелені паростки',
    description: 'Теплиця другого рівня дає більше біоматеріалів для науки.',
    type: 'story',
    chapter: 6,
    order: 3,
    chapterName: 'Ресурси',
    objective: { action: 'upgrade_building', target: 'greenhouse', targetLevel: 2, count: 1 },
    reward: { gold: 300, bio: 50 },
    xpReward: 35,
    nextMission: 'story_6_4',
    requires: 'story_6_2',
    loreText: 'Теплиця дає перший урожай. Їжа — не розкіш, а паливо для думки.',
  },
  {
    id: 'story_6_4',
    title: 'Торговий обмін',
    description: 'Перша торгова операція відкриває шляхи між поселеннями.',
    type: 'story',
    chapter: 6,
    order: 4,
    chapterName: 'Ресурси',
    objective: { action: 'trade', count: 1 },
    reward: { gold: 400, crystals: 10 },
    xpReward: 30,
    nextMission: 'story_6_5',
    requires: 'story_6_3',
    loreText: 'Перший обмін завершено. Ресурси течуть між поселеннями — економіка відроджується.',
  },
  {
    id: 'story_6_5',
    title: 'Запасний фонд',
    description: 'Зберіть достатньо ресурсів для тривалого виживання — здійсни ще 2 торгівлі.',
    type: 'story',
    chapter: 6,
    order: 5,
    chapterName: 'Ресурси',
    objective: { action: 'trade', count: 2 },
    reward: { gold: 500, bits: 80, code: 20 },
    xpReward: 40,
    nextMission: 'story_7_1',
    requires: 'story_6_4',
    loreText: 'Запаси поповнено. Nova Academy готова до наступного кроку.',
  },

  // ─── Глава 7: Армія ───────────────────────────────────────
  {
    id: 'story_7_1',
    title: 'Набір рекрутів',
    description: 'П\'ять юнітів — перша боєздатна армія Академії.',
    type: 'story',
    chapter: 7,
    order: 1,
    chapterName: 'Армія',
    objective: { action: 'recruit_unit', count: 5 },
    reward: { gold: 400, bits: 80 },
    xpReward: 40,
    nextMission: 'story_7_2',
    requires: 'story_6_5',
    loreText: 'П\'ять захисників стоять у строю. Академія показує силу.',
  },
  {
    id: 'story_7_2',
    title: 'Перший рейд',
    description: 'Атакуй руїну тіру 1 — перше бойове хрещення армії.',
    type: 'story',
    chapter: 7,
    order: 2,
    chapterName: 'Армія',
    objective: { action: 'clear_ruin', tier: 1, count: 1 },
    reward: { gold: 600, bits: 120, code: 40 },
    xpReward: 45,
    diamondReward: 1,
    nextMission: 'story_7_3',
    requires: 'story_7_1',
    loreText: 'Перший рейд успішний. Армія загартована. Наступні руїни не будуть легшими.',
  },
  {
    id: 'story_7_3',
    title: 'Ветерани',
    description: 'Десять юнітів — справжня армія, здатна тримати оборону.',
    type: 'story',
    chapter: 7,
    order: 3,
    chapterName: 'Армія',
    objective: { action: 'recruit_unit', count: 10 },
    reward: { gold: 600, bits: 120 },
    xpReward: 50,
    nextMission: 'story_7_4',
    requires: 'story_7_2',
    loreText: 'Десятка ветеранів. Академія стала силою, з якою рахуються.',
  },
  {
    id: 'story_7_4',
    title: 'Двійний штурм',
    description: 'Зачисти дві руїни тіру 1 — очисти прилеглі квартали.',
    type: 'story',
    chapter: 7,
    order: 4,
    chapterName: 'Армія',
    objective: { action: 'clear_ruin', tier: 1, count: 2 },
    reward: { gold: 800, bits: 160, code: 60 },
    xpReward: 55,
    diamondReward: 1,
    nextMission: 'story_7_5',
    requires: 'story_7_3',
    loreText: 'Два квартали зачищено. Карта безпечних зон розширюється.',
  },
  {
    id: 'story_7_5',
    title: 'Командна тактика',
    description: 'Сформуй армію з трьох юнітів різних типів для тактичної переваги.',
    type: 'story',
    chapter: 7,
    order: 5,
    chapterName: 'Армія',
    objective: { action: 'recruit_unit', count: 3 },
    reward: { gold: 500, crystals: 15 },
    xpReward: 40,
    nextMission: 'story_7_6',
    requires: 'story_7_4',
    loreText: 'Тактика відпрацьована. Академія навчає не лише думати, але й захищатися.',
  },
  {
    id: 'story_7_6',
    title: 'Перші втрати і перші перемоги',
    description: 'Зачисти ще одну руїну тіру 1. Армія продовжує рости.',
    type: 'story',
    chapter: 7,
    order: 6,
    chapterName: 'Армія',
    objective: { action: 'clear_ruin', tier: 1, count: 1 },
    reward: { gold: 700, bits: 150, code: 50 },
    xpReward: 50,
    diamondReward: 1,
    nextMission: 'story_8_1',
    requires: 'story_7_5',
    loreText: 'Ще одна перемога. Банк досвіду Академії поповнено.',
  },

  // ─── Глава 8: Розвідка ────────────────────────────────────
  {
    id: 'story_8_1',
    title: 'Картографія',
    description: 'Досліди три клітинки карти — знання місцевості рятує армії.',
    type: 'story',
    chapter: 8,
    order: 1,
    chapterName: 'Розвідка',
    objective: { action: 'start_research', count: 3 },
    reward: { gold: 400, bits: 60 },
    xpReward: 40,
    nextMission: 'story_8_2',
    requires: 'story_7_6',
    loreText: 'Три нових клітинки на карті. Таємниці руїн починають розкриватися.',
  },
  {
    id: 'story_8_2',
    title: 'Рейд на складський вузол',
    description: 'Атакуй руїну тіру 1 — там є запаси старого світу.',
    type: 'story',
    chapter: 8,
    order: 2,
    chapterName: 'Розвідка',
    objective: { action: 'clear_ruin', tier: 1, count: 1 },
    reward: { gold: 700, bits: 140, code: 50 },
    xpReward: 45,
    nextMission: 'story_8_3',
    requires: 'story_8_1',
    loreText: 'Склад зачищено. Запаси — іще один крок до відновлення.',
  },
  {
    id: 'story_8_3',
    title: 'Лабораторія польових досліджень',
    description: 'Покращ лабораторію до рівня 2 для аналізу знахідок.',
    type: 'story',
    chapter: 8,
    order: 3,
    chapterName: 'Розвідка',
    objective: { action: 'upgrade_building', target: 'lab', targetLevel: 2, count: 1 },
    reward: { gold: 500, bits: 100, code: 40 },
    xpReward: 45,
    nextMission: 'story_8_4',
    requires: 'story_8_2',
    loreText: 'Лабораторія другого рівня відкриває доступ до складного аналізу.',
  },
  {
    id: 'story_8_4',
    title: 'Середня загроза',
    description: 'Атакуй руїну тіру 2 — там захищені склади технологій.',
    type: 'story',
    chapter: 8,
    order: 4,
    chapterName: 'Розвідка',
    objective: { action: 'clear_ruin', tier: 2, count: 1 },
    reward: { gold: 1000, bits: 200, code: 80 },
    xpReward: 60,
    diamondReward: 2,
    nextMission: 'story_8_5',
    requires: 'story_8_3',
    loreText: 'Перша руїна тіру 2 впала. Армія Академії — серйозна сила.',
  },
  {
    id: 'story_8_5',
    title: 'Мапа загроз',
    description: 'Досліди п\'ять клітинок карти для повного розуміння ситуації.',
    type: 'story',
    chapter: 8,
    order: 5,
    chapterName: 'Розвідка',
    objective: { action: 'start_research', count: 5 },
    reward: { gold: 500, bits: 80 },
    xpReward: 45,
    nextMission: 'story_9_1',
    requires: 'story_8_4',
    loreText: 'П\'ять нових зон на карті. Руїни більше не мають секретів.',
  },

  // ─── Глава 9: Технологія ──────────────────────────────────
  {
    id: 'story_9_1',
    title: 'Сервер другого покоління',
    description: 'Покращ сервер до рівня 2 — більше пам\'яті, більше можливостей.',
    type: 'story',
    chapter: 9,
    order: 1,
    chapterName: 'Технологія',
    objective: { action: 'upgrade_building', target: 'server', targetLevel: 2, count: 1 },
    reward: { gold: 500, bits: 100, code: 50 },
    xpReward: 50,
    nextMission: 'story_9_2',
    requires: 'story_8_5',
    loreText: 'Сервер другого покоління онлайн. Обчислювальна потужність зросла.',
  },
  {
    id: 'story_9_2',
    title: 'Наукові прориви',
    description: 'Запусти п\'ять досліджень для відновлення наукового потенціалу.',
    type: 'story',
    chapter: 9,
    order: 2,
    chapterName: 'Технологія',
    objective: { action: 'start_research', count: 5 },
    reward: { gold: 400, bits: 80 },
    xpReward: 45,
    nextMission: 'story_9_3',
    requires: 'story_9_1',
    loreText: 'П\'ять нових досліджень. Наука повертається до руїн.',
  },
  {
    id: 'story_9_3',
    title: 'Лабораторія третього рівня',
    description: 'Лабораторія рівня 3 — серце наукових досліджень Академії.',
    type: 'story',
    chapter: 9,
    order: 3,
    chapterName: 'Технологія',
    objective: { action: 'upgrade_building', target: 'lab', targetLevel: 3, count: 1 },
    reward: { gold: 700, bits: 150, code: 80 },
    xpReward: 55,
    nextMission: 'story_9_4',
    requires: 'story_9_2',
    loreText: 'Лабораторія третього рівня — найсучасніша в регіоні. Академія стає науковим центром.',
  },
  {
    id: 'story_9_4',
    title: 'Головний сервер',
    description: 'Сервер рівня 3 контролює всю мережу Академії.',
    type: 'story',
    chapter: 9,
    order: 4,
    chapterName: 'Технологія',
    objective: { action: 'upgrade_building', target: 'server', targetLevel: 3, count: 1 },
    reward: { gold: 800, bits: 200, code: 100 },
    xpReward: 60,
    nextMission: 'story_9_5',
    requires: 'story_9_3',
    loreText: 'Головний сервер тримає базу знань. Академія стала вузлом інформації нового світу.',
  },
  {
    id: 'story_9_5',
    title: 'Десять досліджень',
    description: 'Запусти ще п\'ять досліджень — картографія не закінчена.',
    type: 'story',
    chapter: 9,
    order: 5,
    chapterName: 'Технологія',
    objective: { action: 'start_research', count: 5 },
    reward: { gold: 600, bits: 100, code: 50 },
    xpReward: 50,
    nextMission: 'story_10_1',
    requires: 'story_9_4',
    loreText: 'Карта заповнена ще більше. Знання — єдиний ресурс, що не закінчується.',
  },

  // ─── Глава 10: Торгівля ───────────────────────────────────
  {
    id: 'story_10_1',
    title: 'Торговий маршрут',
    description: 'Здійсни три торгові операції для відновлення ринкових зв\'язків.',
    type: 'story',
    chapter: 10,
    order: 1,
    chapterName: 'Торгівля',
    objective: { action: 'trade', count: 3 },
    reward: { gold: 600, crystals: 15 },
    xpReward: 50,
    nextMission: 'story_10_2',
    requires: 'story_9_5',
    loreText: 'Три угоди. Торговий маршрут між поселеннями офіційно відкрито.',
  },
  {
    id: 'story_10_2',
    title: 'Регулярна торгівля',
    description: 'П\'ять торгових операцій — ринок починає функціонувати стабільно.',
    type: 'story',
    chapter: 10,
    order: 2,
    chapterName: 'Торгівля',
    objective: { action: 'trade', count: 5 },
    reward: { gold: 800, crystals: 20 },
    xpReward: 55,
    nextMission: 'story_10_3',
    requires: 'story_10_1',
    loreText: 'Ринок відроджується. Обмін товарами — це мир між поселеннями.',
  },
  {
    id: 'story_10_3',
    title: 'Комерційний вузол',
    description: 'Покращ вежу зв\'язку до рівня 3 — більший радіус, більше партнерів.',
    type: 'story',
    chapter: 10,
    order: 3,
    chapterName: 'Торгівля',
    objective: { action: 'upgrade_building', target: 'tower', targetLevel: 3, count: 1 },
    reward: { gold: 700, code: 60 },
    xpReward: 55,
    nextMission: 'story_10_4',
    requires: 'story_10_2',
    loreText: 'Вежа третього рівня. Сигнал сягає найвіддаленіших поселень.',
  },
  {
    id: 'story_10_4',
    title: 'Десять угод',
    description: 'Десять торгових операцій — Академія стала торговим центром регіону.',
    type: 'story',
    chapter: 10,
    order: 4,
    chapterName: 'Торгівля',
    objective: { action: 'trade', count: 10 },
    reward: { gold: 1200, crystals: 30 },
    xpReward: 65,
    diamondReward: 1,
    nextMission: 'story_10_5',
    requires: 'story_10_3',
    loreText: 'Десята угода підписана. Економіка нового світу набирає оберти.',
  },
  {
    id: 'story_10_5',
    title: 'Ринкова держава',
    description: 'Покращ шахту до рівня 3 і забезпеч стабільне постачання ресурсів.',
    type: 'story',
    chapter: 10,
    order: 5,
    chapterName: 'Торгівля',
    objective: { action: 'upgrade_building', target: 'mine', targetLevel: 3, count: 1 },
    reward: { gold: 1000, bits: 200 },
    xpReward: 65,
    nextMission: 'story_11_1',
    requires: 'story_10_4',
    loreText: 'Шахта третього рівня. Видобуток максимальний. Ресурси більше не проблема.',
  },

  // ─── Глава 11: Відновлення ────────────────────────────────
  {
    id: 'story_11_1',
    title: 'Зелена енергія',
    description: 'Реактор або сонячна батарея другого рівня — чиста енергія для Академії.',
    type: 'story',
    chapter: 11,
    order: 1,
    chapterName: 'Відновлення',
    objective: { action: 'upgrade_building', target: ['reactor', 'solar_array'], targetLevel: 2, count: 1 },
    reward: { gold: 600, energy: 60 },
    xpReward: 55,
    nextMission: 'story_11_2',
    requires: 'story_10_5',
    loreText: 'Чиста енергія тече в Академію. Старий світ руйнував природу. Новий — відновлює.',
  },
  {
    id: 'story_11_2',
    title: 'Теплиця третього рівня',
    description: 'Повна теплиця — самодостатній центр виробництва біоматеріалів.',
    type: 'story',
    chapter: 11,
    order: 2,
    chapterName: 'Відновлення',
    objective: { action: 'upgrade_building', target: 'greenhouse', targetLevel: 3, count: 1 },
    reward: { gold: 700, bio: 100 },
    xpReward: 60,
    nextMission: 'story_11_3',
    requires: 'story_11_1',
    loreText: 'Теплиця розцвіла. Рослини, яких не було роками — тепер живі. Природа прощає.',
  },
  {
    id: 'story_11_3',
    title: 'Друга руїна тіру 2',
    description: 'Зачисти другу руїну тіру 2 — там можуть бути ключі до нових технологій.',
    type: 'story',
    chapter: 11,
    order: 3,
    chapterName: 'Відновлення',
    objective: { action: 'clear_ruin', tier: 2, count: 1 },
    reward: { gold: 1200, bits: 250, bio: 80 },
    xpReward: 70,
    diamondReward: 2,
    nextMission: 'story_11_4',
    requires: 'story_11_2',
    loreText: 'Ще одна руїна тіру 2 зачищена. Технологічні артефакти відновлено.',
  },
  {
    id: 'story_11_4',
    title: 'Енергетичний надлишок',
    description: 'Три торгівлі для продажу надлишку енергії сусіднім поселенням.',
    type: 'story',
    chapter: 11,
    order: 4,
    chapterName: 'Відновлення',
    objective: { action: 'trade', count: 3 },
    reward: { gold: 800, energy: 80 },
    xpReward: 55,
    nextMission: 'story_11_5',
    requires: 'story_11_3',
    loreText: 'Академія продає енергію сусідам. Перший крок до регіональної мережі.',
  },
  {
    id: 'story_11_5',
    title: 'Твердиня',
    description: 'Замок четвертого рівня — Академія стає регіональним центром.',
    type: 'story',
    chapter: 11,
    order: 5,
    chapterName: 'Відновлення',
    objective: { action: 'upgrade_castle', targetLevel: 4, count: 1 },
    reward: { gold: 1200, stone: 300, crystals: 50 },
    xpReward: 80,
    diamondReward: 2,
    nextMission: 'story_12_1',
    requires: 'story_11_4',
    loreText: 'Твердиня — чотири рівні зміцнень. Академія непорушна.',
  },

  // ─── Глава 12: Зброя ──────────────────────────────────────
  {
    id: 'story_12_1',
    title: 'П\'ятнадцять бійців',
    description: 'П\'ятнадцять юнітів формують армію здатну тримати будь-який рубіж.',
    type: 'story',
    chapter: 12,
    order: 1,
    chapterName: 'Зброя',
    objective: { action: 'recruit_unit', count: 15 },
    reward: { gold: 1000, bits: 200 },
    xpReward: 70,
    nextMission: 'story_12_2',
    requires: 'story_11_5',
    loreText: 'П\'ятнадцять бійців. Академія — фортеця з власною армією.',
  },
  {
    id: 'story_12_2',
    title: 'Подвійний штурм тіру 2',
    description: 'Зачисти дві руїни тіру 2 — армія потребує бойового загартування.',
    type: 'story',
    chapter: 12,
    order: 2,
    chapterName: 'Зброя',
    objective: { action: 'clear_ruin', tier: 2, count: 2 },
    reward: { gold: 2000, bits: 400, code: 150 },
    xpReward: 80,
    diamondReward: 2,
    nextMission: 'story_12_3',
    requires: 'story_12_1',
    loreText: 'Дві руїни тіру 2 зачищені. Армія стала елітою серед виживших.',
  },
  {
    id: 'story_12_3',
    title: 'Техніки підготовлені',
    description: 'Покращ сервер і лабораторію до рівня 3 для технологічної переваги.',
    type: 'story',
    chapter: 12,
    order: 3,
    chapterName: 'Зброя',
    objective: { action: 'upgrade_building', target: 'server', targetLevel: 3, count: 1 },
    reward: { gold: 900, bits: 180, code: 90 },
    xpReward: 70,
    nextMission: 'story_12_4',
    requires: 'story_12_2',
    loreText: 'Технологічна перевага здобута. Академія веде нову гонку озброєнь.',
  },
  {
    id: 'story_12_4',
    title: 'Третій шторм',
    description: 'Зачисти ще три руїни тіру 2 для повного контролю над регіоном.',
    type: 'story',
    chapter: 12,
    order: 4,
    chapterName: 'Зброя',
    objective: { action: 'clear_ruin', tier: 2, count: 3 },
    reward: { gold: 2500, bits: 500, code: 200 },
    xpReward: 90,
    diamondReward: 3,
    nextMission: 'story_12_5',
    requires: 'story_12_3',
    loreText: 'Три додаткові руїни зачищені. Регіон під контролем Nova Academy.',
  },
  {
    id: 'story_12_5',
    title: 'Фінальне озброєння',
    description: 'Двадцять юнітів — максимальна бойова сила Академії.',
    type: 'story',
    chapter: 12,
    order: 5,
    chapterName: 'Зброя',
    objective: { action: 'recruit_unit', count: 20 },
    reward: { gold: 1500, bits: 300 },
    xpReward: 80,
    nextMission: 'story_12_6',
    requires: 'story_12_4',
    loreText: 'Двадцять захисників. Академія — найсильніша сила в регіоні.',
  },
  {
    id: 'story_12_6',
    title: 'Технологічний прорив',
    description: 'Покращ лабораторію до рівня 3 для максимального наукового потенціалу.',
    type: 'story',
    chapter: 12,
    order: 6,
    chapterName: 'Зброя',
    objective: { action: 'upgrade_building', target: 'lab', targetLevel: 3, count: 1 },
    reward: { gold: 1000, code: 150, crystals: 30 },
    xpReward: 75,
    nextMission: 'story_13_1',
    requires: 'story_12_5',
    loreText: 'Лабораторія максимального рівня. Наука Академії не знає меж.',
  },

  // ─── Глава 13: Союзники ───────────────────────────────────
  {
    id: 'story_13_1',
    title: 'Мережа зв\'язку',
    description: 'Вежа рівня 4 охоплює весь регіон — стратегічна перевага.',
    type: 'story',
    chapter: 13,
    order: 1,
    chapterName: 'Союзники',
    objective: { action: 'upgrade_building', target: 'tower', targetLevel: 4, count: 1 },
    reward: { gold: 1000, code: 100 },
    xpReward: 75,
    nextMission: 'story_13_2',
    requires: 'story_12_6',
    loreText: 'Вежа четвертого рівня — сигнал чутно скрізь. Союзники починають збиратися.',
  },
  {
    id: 'story_13_2',
    title: 'П\'ятнадцять угод',
    description: 'Активна торгівля зміцнює союзи між поселеннями.',
    type: 'story',
    chapter: 13,
    order: 2,
    chapterName: 'Союзники',
    objective: { action: 'trade', count: 15 },
    reward: { gold: 2000, crystals: 50 },
    xpReward: 80,
    diamondReward: 2,
    nextMission: 'story_13_3',
    requires: 'story_13_1',
    loreText: 'П\'ятнадцять угод. Мережа союзників охоплює регіон.',
  },
  {
    id: 'story_13_3',
    title: 'Сервер четвертого покоління',
    description: 'Сервер рівня 4 — хмарні обчислення для нового світу.',
    type: 'story',
    chapter: 13,
    order: 3,
    chapterName: 'Союзники',
    objective: { action: 'upgrade_building', target: 'server', targetLevel: 4, count: 1 },
    reward: { gold: 1200, bits: 300, code: 150 },
    xpReward: 80,
    nextMission: 'story_13_4',
    requires: 'story_13_2',
    loreText: 'Сервер четвертого покоління. Академія керує найпотужнішою мережею в регіоні.',
  },
  {
    id: 'story_13_4',
    title: 'Об\'єднана розвідка',
    description: 'Досліди десять клітинок разом із союзниками.',
    type: 'story',
    chapter: 13,
    order: 4,
    chapterName: 'Союзники',
    objective: { action: 'start_research', count: 10 },
    reward: { gold: 900, bits: 180 },
    xpReward: 75,
    nextMission: 'story_13_5',
    requires: 'story_13_3',
    loreText: 'Десять зон досліджено. Карта відкрита — більше немає сліпих плям.',
  },
  {
    id: 'story_13_5',
    title: 'Тридцять захисників',
    description: 'Тридцять юнітів — достатньо для захисту цілого регіону.',
    type: 'story',
    chapter: 13,
    order: 5,
    chapterName: 'Союзники',
    objective: { action: 'recruit_unit', count: 30 },
    reward: { gold: 2000, bits: 400 },
    xpReward: 90,
    nextMission: 'story_14_1',
    requires: 'story_13_4',
    loreText: 'Тридцять захисників. Академія — щит регіону.',
  },

  // ─── Глава 14: Таємниці ───────────────────────────────────
  {
    id: 'story_14_1',
    title: 'Три руїни тіру 2',
    description: 'Зачисти три руїни тіру 2 — там заховані секретні лабораторії.',
    type: 'story',
    chapter: 14,
    order: 1,
    chapterName: 'Таємниці',
    objective: { action: 'clear_ruin', tier: 2, count: 3 },
    reward: { gold: 3000, bits: 600, code: 200 },
    xpReward: 90,
    diamondReward: 3,
    nextMission: 'story_14_2',
    requires: 'story_13_5',
    loreText: 'Три секретні лабораторії зачищено. Дані, яких немає більше ніде.',
  },
  {
    id: 'story_14_2',
    title: 'Лабораторія четвертого рівня',
    description: 'Лабораторія рівня 4 відкриває секрети, які мало хто бачив.',
    type: 'story',
    chapter: 14,
    order: 2,
    chapterName: 'Таємниці',
    objective: { action: 'upgrade_building', target: 'lab', targetLevel: 4, count: 1 },
    reward: { gold: 1500, bits: 350, code: 180 },
    xpReward: 90,
    nextMission: 'story_14_3',
    requires: 'story_14_1',
    loreText: 'Лабораторія четвертого рівня. Розшифровка артефактів Колапсу розпочалась.',
  },
  {
    id: 'story_14_3',
    title: 'Перша руїна тіру 3',
    description: 'Атакуй руїну тіру 3 — тут зберігається щось важливе.',
    type: 'story',
    chapter: 14,
    order: 3,
    chapterName: 'Таємниці',
    objective: { action: 'clear_ruin', tier: 3, count: 1 },
    reward: { gold: 3500, bits: 700, code: 300, crystals: 100 },
    xpReward: 100,
    diamondReward: 3,
    nextMission: 'story_14_4',
    requires: 'story_14_2',
    loreText: 'Руїна тіру 3 впала. Всередині — частина "Протоколу Відродження". Не остання.',
  },
  {
    id: 'story_14_4',
    title: 'Двадцять угод',
    description: 'Двадцять торгових операцій закріплюють позицію Академії як центру торгівлі.',
    type: 'story',
    chapter: 14,
    order: 4,
    chapterName: 'Таємниці',
    objective: { action: 'trade', count: 20 },
    reward: { gold: 3000, crystals: 80 },
    xpReward: 85,
    diamondReward: 2,
    nextMission: 'story_14_5',
    requires: 'story_14_3',
    loreText: 'Двадцять угод. Академія — економічна столиця нового світу.',
  },
  {
    id: 'story_14_5',
    title: 'Архів знань',
    description: 'Запусти п\'ятнадцять досліджень — архів Nova Academy поповнюється.',
    type: 'story',
    chapter: 14,
    order: 5,
    chapterName: 'Таємниці',
    objective: { action: 'start_research', count: 15 },
    reward: { gold: 1500, bits: 300, code: 150 },
    xpReward: 90,
    nextMission: 'story_15_1',
    requires: 'story_14_4',
    loreText: 'П\'ятнадцять досліджень. База знань Академії — найбільша в регіоні.',
  },

  // ─── Глава 15: Фронтир ────────────────────────────────────
  {
    id: 'story_15_1',
    title: 'Розширення замку',
    description: 'Замок четвертого рівня утримує зростаючу Академію.',
    type: 'story',
    chapter: 15,
    order: 1,
    chapterName: 'Фронтир',
    objective: { action: 'upgrade_castle', targetLevel: 4, count: 1 },
    reward: { gold: 2000, stone: 500, crystals: 80 },
    xpReward: 100,
    diamondReward: 2,
    nextMission: 'story_15_2',
    requires: 'story_14_5',
    loreText: 'Четвертий рівень замку завершено. Академія — місто серед руїн.',
  },
  {
    id: 'story_15_2',
    title: 'Глибоке сканування',
    description: 'Двадцять досліджень відкривають останні таємниці карти.',
    type: 'story',
    chapter: 15,
    order: 2,
    chapterName: 'Фронтир',
    objective: { action: 'start_research', count: 20 },
    reward: { gold: 2000, bits: 400 },
    xpReward: 100,
    nextMission: 'story_15_3',
    requires: 'story_15_1',
    loreText: 'Двадцять досліджень. Карта майже повна. Що ховається в останніх руїнах?',
  },
  {
    id: 'story_15_3',
    title: 'Дві руїни тіру 3',
    description: 'Зачисти дві руїни тіру 3 для завершення зачистки регіону.',
    type: 'story',
    chapter: 15,
    order: 3,
    chapterName: 'Фронтир',
    objective: { action: 'clear_ruin', tier: 3, count: 2 },
    reward: { gold: 6000, bits: 1200, code: 500, bio: 200 },
    xpReward: 120,
    diamondReward: 4,
    nextMission: 'story_15_4',
    requires: 'story_15_2',
    loreText: 'Дві руїни тіру 3 зачищені. Регіон практично безпечний.',
  },
  {
    id: 'story_15_4',
    title: 'Сервер п\'ятого покоління',
    description: 'Сервер рівня 5 — вершина технологій нового світу.',
    type: 'story',
    chapter: 15,
    order: 4,
    chapterName: 'Фронтир',
    objective: { action: 'upgrade_building', target: 'server', targetLevel: 5, count: 1 },
    reward: { gold: 2500, bits: 600, code: 300 },
    xpReward: 120,
    diamondReward: 3,
    nextMission: 'story_15_5',
    requires: 'story_15_3',
    loreText: 'Сервер п\'ятого покоління. Академія — технологічна вершина нового світу.',
  },
  {
    id: 'story_15_5',
    title: 'Сорок бійців',
    description: 'Сорок юнітів формують армію, здатну захистити цілу країну.',
    type: 'story',
    chapter: 15,
    order: 5,
    chapterName: 'Фронтир',
    objective: { action: 'recruit_unit', count: 40 },
    reward: { gold: 3000, bits: 600 },
    xpReward: 110,
    nextMission: 'story_16_1',
    requires: 'story_15_4',
    loreText: 'Сорок захисників. Армія Академії — легенда нового світу.',
  },

  // ─── Глава 16: Академія ───────────────────────────────────
  {
    id: 'story_16_1',
    title: 'Вежа зв\'язку максимальна',
    description: 'Вежа рівня 5 з\'єднує всі поселення регіону.',
    type: 'story',
    chapter: 16,
    order: 1,
    chapterName: 'Академія',
    objective: { action: 'upgrade_building', target: 'tower', targetLevel: 5, count: 1 },
    reward: { gold: 2000, code: 200 },
    xpReward: 110,
    nextMission: 'story_16_2',
    requires: 'story_15_5',
    loreText: 'Вежа рівня 5. Академія говорить — весь регіон чує.',
  },
  {
    id: 'story_16_2',
    title: 'Тридцять угод',
    description: 'Тридцять торгових операцій — Академія є центром економіки.',
    type: 'story',
    chapter: 16,
    order: 2,
    chapterName: 'Академія',
    objective: { action: 'trade', count: 30 },
    reward: { gold: 4000, crystals: 100 },
    xpReward: 110,
    diamondReward: 3,
    nextMission: 'story_16_3',
    requires: 'story_16_1',
    loreText: 'Тридцята угода. Нова економіка побудована на довірі, а не на страху.',
  },
  {
    id: 'story_16_3',
    title: 'Лабораторія п\'ятого рівня',
    description: 'Лабораторія рівня 5 — максимум науки в новому світі.',
    type: 'story',
    chapter: 16,
    order: 3,
    chapterName: 'Академія',
    objective: { action: 'upgrade_building', target: 'lab', targetLevel: 5, count: 1 },
    reward: { gold: 3000, bits: 700, code: 400 },
    xpReward: 120,
    diamondReward: 3,
    nextMission: 'story_16_4',
    requires: 'story_16_2',
    loreText: 'Лабораторія п\'ятого рівня. Питання більше немає — лише відповіді.',
  },
  {
    id: 'story_16_4',
    title: 'Тридцять досліджень',
    description: 'Тридцять досліджень — повне картографування руїн регіону.',
    type: 'story',
    chapter: 16,
    order: 4,
    chapterName: 'Академія',
    objective: { action: 'start_research', count: 30 },
    reward: { gold: 3000, bits: 600, code: 300 },
    xpReward: 120,
    nextMission: 'story_16_5',
    requires: 'story_16_3',
    loreText: 'Тридцять досліджень. Карта повна. Nova Academy знає всі таємниці регіону.',
  },
  {
    id: 'story_16_5',
    title: 'Три руїни тіру 3 більше',
    description: 'Зачисти ще три руїни тіру 3 для звільнення останніх захоплених зон.',
    type: 'story',
    chapter: 16,
    order: 5,
    chapterName: 'Академія',
    objective: { action: 'clear_ruin', tier: 3, count: 3 },
    reward: { gold: 8000, bits: 1500, code: 600, energy: 300 },
    xpReward: 130,
    diamondReward: 4,
    nextMission: 'story_17_1',
    requires: 'story_16_4',
    loreText: 'Три нові перемоги. Регіон повністю під контролем Nova Academy.',
  },

  // ─── Глава 17: Архів ──────────────────────────────────────
  {
    id: 'story_17_1',
    title: 'Остаточна теплиця',
    description: 'Теплиця максимального рівня — повна продовольча незалежність.',
    type: 'story',
    chapter: 17,
    order: 1,
    chapterName: 'Архів',
    objective: { action: 'upgrade_building', target: 'greenhouse', targetLevel: 5, count: 1 },
    reward: { gold: 2500, bio: 200 },
    xpReward: 120,
    nextMission: 'story_17_2',
    requires: 'story_16_5',
    loreText: 'Теплиця на максимумі. Академія забезпечує себе їжею і продає надлишки.',
  },
  {
    id: 'story_17_2',
    title: 'Енергетична незалежність',
    description: 'Реактор або сонячна батарея рівня 5 — повна енергетична незалежність.',
    type: 'story',
    chapter: 17,
    order: 2,
    chapterName: 'Архів',
    objective: { action: 'upgrade_building', target: ['reactor', 'solar_array'], targetLevel: 5, count: 1 },
    reward: { gold: 3000, energy: 200 },
    xpReward: 130,
    nextMission: 'story_17_3',
    requires: 'story_17_1',
    loreText: 'Максимальна енергетика. Академія виробляє більше енергії, ніж споживає.',
  },
  {
    id: 'story_17_3',
    title: 'П\'ятдесят захисників',
    description: 'П\'ятдесят юнітів — армія, здатна захистити ціле королівство.',
    type: 'story',
    chapter: 17,
    order: 3,
    chapterName: 'Архів',
    objective: { action: 'recruit_unit', count: 50 },
    reward: { gold: 4000, bits: 800 },
    xpReward: 130,
    nextMission: 'story_17_4',
    requires: 'story_17_2',
    loreText: 'П\'ятдесят захисників. Ніхто більше не загрожує Nova Academy.',
  },
  {
    id: 'story_17_4',
    title: 'Четверта руїна тіру 3',
    description: 'Зачисти ще дві руїни тіру 3 — останні осередки небезпеки.',
    type: 'story',
    chapter: 17,
    order: 4,
    chapterName: 'Архів',
    objective: { action: 'clear_ruin', tier: 3, count: 2 },
    reward: { gold: 8000, bits: 1600, code: 700, crystals: 200 },
    xpReward: 140,
    diamondReward: 4,
    nextMission: 'story_17_5',
    requires: 'story_17_3',
    loreText: 'Ще дві руїни тіру 3 впали. Регіон очищено.',
  },
  {
    id: 'story_17_5',
    title: 'Сорок угод',
    description: 'Сорок торгових операцій — Академія є центром глобальної торгівлі нового світу.',
    type: 'story',
    chapter: 17,
    order: 5,
    chapterName: 'Архів',
    objective: { action: 'trade', count: 40 },
    reward: { gold: 5000, crystals: 120 },
    xpReward: 130,
    diamondReward: 3,
    nextMission: 'story_18_1',
    requires: 'story_17_4',
    loreText: 'Сорок угод. Економічна мережа нового світу повністю відновлена.',
  },

  // ─── Глава 18: Кризис ─────────────────────────────────────
  {
    id: 'story_18_1',
    title: 'Загроза з тіні',
    description: 'Зачисти чотири руїни тіру 3 — відкрита атака на Академію.',
    type: 'story',
    chapter: 18,
    order: 1,
    chapterName: 'Кризис',
    objective: { action: 'clear_ruin', tier: 3, count: 4 },
    reward: { gold: 10000, bits: 2000, code: 800 },
    xpReward: 140,
    diamondReward: 5,
    nextMission: 'story_18_2',
    requires: 'story_17_5',
    loreText: 'Чотири кризові точки усунуто. Але загроза не минула — вони повертаються.',
  },
  {
    id: 'story_18_2',
    title: 'Замок п\'ятого рівня',
    description: 'Фортеця максимального рівня — остання лінія оборони Академії.',
    type: 'story',
    chapter: 18,
    order: 2,
    chapterName: 'Кризис',
    objective: { action: 'upgrade_castle', targetLevel: 5, count: 1 },
    reward: { gold: 5000, stone: 1000, crystals: 200 },
    xpReward: 150,
    diamondReward: 5,
    nextMission: 'story_18_3',
    requires: 'story_18_1',
    loreText: 'П\'ятий рівень замку. Nova Academy — неприступна фортеця нового світу.',
  },
  {
    id: 'story_18_3',
    title: 'Масовий набір',
    description: 'Шістдесят юнітів для відбиття масштабного нападу.',
    type: 'story',
    chapter: 18,
    order: 3,
    chapterName: 'Кризис',
    objective: { action: 'recruit_unit', count: 60 },
    reward: { gold: 6000, bits: 1200 },
    xpReward: 140,
    nextMission: 'story_18_4',
    requires: 'story_18_2',
    loreText: 'Шістдесят захисників. Академія готова до будь-якого нападу.',
  },
  {
    id: 'story_18_4',
    title: 'Оборона рубежу',
    description: 'Вежа четвертого рівня і п\'ять додаткових досліджень — система раннього сповіщення.',
    type: 'story',
    chapter: 18,
    order: 4,
    chapterName: 'Кризис',
    objective: { action: 'start_research', count: 5 },
    reward: { gold: 3000, bits: 500 },
    xpReward: 130,
    nextMission: 'story_18_5',
    requires: 'story_18_3',
    loreText: 'Система раннього сповіщення активована. Жодна загроза не застане Академію зненацька.',
  },
  {
    id: 'story_18_5',
    title: 'Контратака',
    description: 'П\'ять руїн тіру 3 — повна зачистка небезпечних зон.',
    type: 'story',
    chapter: 18,
    order: 5,
    chapterName: 'Кризис',
    objective: { action: 'clear_ruin', tier: 3, count: 5 },
    reward: { gold: 12000, bits: 2500, code: 1000, energy: 500 },
    xpReward: 150,
    diamondReward: 5,
    nextMission: 'story_19_1',
    requires: 'story_18_4',
    loreText: 'П\'ять руїн тіру 3 знищено. Криза пройдена. Академія вистояла.',
  },

  // ─── Глава 19: Відплата ───────────────────────────────────
  {
    id: 'story_19_1',
    title: 'Сімдесят бійців',
    description: 'Сімдесят юнітів — легендарна армія, яку не здолати.',
    type: 'story',
    chapter: 19,
    order: 1,
    chapterName: 'Відплата',
    objective: { action: 'recruit_unit', count: 70 },
    reward: { gold: 8000, bits: 1600 },
    xpReward: 150,
    nextMission: 'story_19_2',
    requires: 'story_18_5',
    loreText: 'Сімдесят захисників — армія легенда. Вороги навіть не намагаються нападати.',
  },
  {
    id: 'story_19_2',
    title: 'Фінальна зачистка тіру 3',
    description: 'Зачисти три останні руїни тіру 3 — фінальна зачистка регіону.',
    type: 'story',
    chapter: 19,
    order: 2,
    chapterName: 'Відплата',
    objective: { action: 'clear_ruin', tier: 3, count: 3 },
    reward: { gold: 12000, bits: 2500, code: 1000 },
    xpReward: 150,
    diamondReward: 5,
    nextMission: 'story_19_3',
    requires: 'story_19_1',
    loreText: 'Три останні руїни тіру 3 знищено. Регіон повністю безпечний.',
  },
  {
    id: 'story_19_3',
    title: 'П\'ятдесят угод',
    description: 'П\'ятдесят торгових операцій — Академія є центром нової цивілізації.',
    type: 'story',
    chapter: 19,
    order: 3,
    chapterName: 'Відплата',
    objective: { action: 'trade', count: 50 },
    reward: { gold: 8000, crystals: 200 },
    xpReward: 140,
    diamondReward: 4,
    nextMission: 'story_19_4',
    requires: 'story_19_2',
    loreText: 'П\'ятдесята угода. Нова цивілізація побудована на торгівлі і знаннях.',
  },
  {
    id: 'story_19_4',
    title: 'Перший бастіон тіру 4',
    description: 'Атакуй руїну тіру 4 — там захований фінальний Протокол Відродження.',
    type: 'story',
    chapter: 19,
    order: 4,
    chapterName: 'Відплата',
    objective: { action: 'clear_ruin', tier: 4, count: 1 },
    reward: { gold: 15000, bits: 3000, code: 1500, crystals: 500 },
    xpReward: 200,
    diamondReward: 8,
    nextMission: 'story_19_5',
    requires: 'story_19_3',
    loreText: 'Перша руїна тіру 4 впала. Всередині — фінальний Протокол Відродження. Частина третя.',
  },
  {
    id: 'story_19_5',
    title: 'Сорок досліджень',
    description: 'Сорок досліджень відкривають останні таємниці нового світу.',
    type: 'story',
    chapter: 19,
    order: 5,
    chapterName: 'Відплата',
    objective: { action: 'start_research', count: 40 },
    reward: { gold: 6000, bits: 1200, code: 600 },
    xpReward: 140,
    nextMission: 'story_20_1',
    requires: 'story_19_4',
    loreText: 'Сорок досліджень. Остання таємниця розкрита. Nova Academy знає правду про Колапс.',
  },

  // ─── Глава 20: Відродження ────────────────────────────────
  {
    id: 'story_20_1',
    title: 'Мегаармія',
    description: 'Вісімдесят юнітів — непереможна армія Nova Academy.',
    type: 'story',
    chapter: 20,
    order: 1,
    chapterName: 'Відродження',
    objective: { action: 'recruit_unit', count: 80 },
    reward: { gold: 10000, bits: 2000 },
    xpReward: 150,
    nextMission: 'story_20_2',
    requires: 'story_19_5',
    loreText: 'Вісімдесят захисників. Армія Nova Academy — найсильніша в новому світі.',
  },
  {
    id: 'story_20_2',
    title: 'Подвійний тір 4',
    description: 'Зачисти дві руїни тіру 4 — фінальний штурм сил хаосу.',
    type: 'story',
    chapter: 20,
    order: 2,
    chapterName: 'Відродження',
    objective: { action: 'clear_ruin', tier: 4, count: 2 },
    reward: { gold: 25000, bits: 5000, code: 2000, crystals: 800, bio: 500, energy: 500 },
    xpReward: 200,
    diamondReward: 10,
    nextMission: 'story_20_3',
    requires: 'story_20_1',
    loreText: 'Дві руїни тіру 4 знищено. Протокол Відродження зібраний повністю. Нова цивілізація народжується.',
  },
  {
    id: 'story_20_3',
    title: 'Остаточна твердиня',
    description: 'Замок рівня 5 — символ перемоги над хаосом Колапсу.',
    type: 'story',
    chapter: 20,
    order: 3,
    chapterName: 'Відродження',
    objective: { action: 'upgrade_castle', targetLevel: 5, count: 1 },
    reward: { gold: 10000, stone: 2000, crystals: 500 },
    xpReward: 200,
    diamondReward: 5,
    nextMission: 'story_20_4',
    requires: 'story_20_2',
    loreText: 'Замок п\'ятого рівня. Nova Academy — нова столиця відродженої цивілізації.',
  },
  {
    id: 'story_20_4',
    title: 'Сімдесят угод',
    description: 'Сімдесят торгових операцій — остаточний акт відновлення цивілізації.',
    type: 'story',
    chapter: 20,
    order: 4,
    chapterName: 'Відродження',
    objective: { action: 'trade', count: 70 },
    reward: { gold: 12000, crystals: 300 },
    xpReward: 150,
    diamondReward: 5,
    nextMission: 'story_20_5',
    requires: 'story_20_3',
    loreText: 'Сімдесята угода підписана. Цивілізація відновлена — не завдяки силі, а завдяки знанням і торгівлі.',
  },
  {
    id: 'story_20_5',
    title: 'Відродження',
    description: 'Збудуй Nova Academy до максимального рівня. Це кінець руїн і початок нового світу.',
    type: 'story',
    chapter: 20,
    order: 5,
    chapterName: 'Відродження',
    objective: { action: 'recruit_unit', count: 100 },
    reward: { gold: 50000, bits: 10000, code: 5000, crystals: 2000, bio: 1000, energy: 1000 },
    xpReward: 500,
    diamondReward: 20,
    nextMission: null,
    requires: 'story_20_4',
    loreText: 'Сто захисників. Протокол Відродження виконаний. Nova Academy завершила свою місію. 2047 рік — рік, коли людство повернулося з руїн. Ти це зробив.',
  },
]

export const DEFAULT_ACHIEVEMENTS = [
  // ─── Будівництво ───
  { id: 'ach_first_building', title: 'Перший камінь', description: 'Побудуй першу будівлю', objective: { action: 'upgrade_building', count: 1 }, reward: {}, diamondReward: 1, icon: '🧱' },
  { id: 'ach_all_buildings', title: 'Містобудівник', description: 'Збудуй всі 5 основних будівель', objective: { action: 'own_buildings', count: 5 }, reward: { gold: 500 }, diamondReward: 2, icon: '🏗️' },
  { id: 'ach_max_building', title: 'Максимальна потужність', description: 'Покращи будь-яку будівлю до рівня 3', objective: { action: 'building_level', targetLevel: 3, count: 1 }, reward: { gold: 300 }, diamondReward: 1, icon: '⚡' },
  { id: 'ach_all_natural', title: 'Науковець', description: 'Збудуй всі 4 будівлі природничих наук', objective: { action: 'own_natural_buildings', count: 4 }, reward: { bio: 50, energy: 50 }, diamondReward: 3, icon: '🔬' },

  // ─── Копальні ───
  { id: 'ach_first_mine', title: 'Золота жила', description: 'Побудуй першу копальню', objective: { action: 'build_mine', count: 1 }, reward: { gold: 100 }, diamondReward: 1, icon: '⛏️' },
  { id: 'ach_5_mines', title: 'Магнат', description: 'Маєш 5 копалень', objective: { action: 'own_mines', count: 5 }, reward: { gold: 500 }, diamondReward: 2, icon: '💰' },
  { id: 'ach_collect_1000', title: 'Збирач тисячі', description: 'Зібрати 1000 ресурсів з копалень', objective: { action: 'collect_total', count: 1000 }, reward: { gold: 300 }, diamondReward: 1, icon: '🏆' },

  // ─── Бій ───
  { id: 'ach_first_battle', title: 'Хрещення вогнем', description: 'Вижити в першому бою', objective: { action: 'battle', count: 1 }, reward: { gold: 200 }, diamondReward: 1, icon: '⚔️' },
  { id: 'ach_10_wins', title: 'Ветеран', description: 'Перемогти 10 разів', objective: { action: 'win_battle', count: 10 }, reward: { gold: 500 }, diamondReward: 3, icon: '🎖️' },
  { id: 'ach_tier3_clear', title: 'Легенда', description: 'Зачистити Бункер Старого Світу', objective: { action: 'clear_ruin', tier: 3, count: 1 }, reward: { gold: 1000 }, diamondReward: 5, icon: '👑' },

  // ─── Армія ───
  { id: 'ach_first_unit', title: 'Командир', description: 'Найняти першого юніта', objective: { action: 'recruit_unit', count: 1 }, reward: { gold: 100 }, diamondReward: 1, icon: '🤖' },
  { id: 'ach_full_army', title: 'Генерал', description: 'Мати 15 юнітів (максимум)', objective: { action: 'own_units', count: 15 }, reward: { gold: 800 }, diamondReward: 3, icon: '🎖️' },
  { id: 'ach_all_unit_types', title: 'Колекціонер', description: 'Мати хоча б по 1 юніту кожного типу', objective: { action: 'own_unit_types', count: 8 }, reward: { gold: 600 }, diamondReward: 2, icon: '🃏' },

  // ─── Замок ───
  { id: 'ach_castle_3', title: 'Фортифікатор', description: 'Замок рівня 3', objective: { action: 'castle_level', targetLevel: 3, count: 1 }, reward: { gold: 500 }, diamondReward: 2, icon: '🏰' },
  { id: 'ach_castle_5', title: 'Імператор', description: 'Замок рівня 5', objective: { action: 'castle_level', targetLevel: 5, count: 1 }, reward: { gold: 2000 }, diamondReward: 5, icon: '👑' },

  // ─── Торгівля ───
  { id: 'ach_first_trade', title: 'Купець', description: 'Здійснити першу торгову операцію', objective: { action: 'trade', count: 1 }, reward: { gold: 100 }, diamondReward: 1, icon: '🤝' },
  { id: 'ach_10_trades', title: 'Торговий барон', description: 'Здійснити 10 операцій', objective: { action: 'trade', count: 10 }, reward: { gold: 400 }, diamondReward: 2, icon: '💎' },

  // ─── Навчання ───
  { id: 'ach_first_task', title: 'Учень', description: 'Виконати перше завдання', objective: { action: 'complete_task', count: 1 }, reward: { gold: 100 }, diamondReward: 1, icon: '📚' },
  { id: 'ach_10_tasks', title: 'Знавець', description: 'Виконати 10 завдань', objective: { action: 'complete_task', count: 10 }, reward: { gold: 500 }, diamondReward: 3, icon: '🎓' },
  { id: 'ach_perfect_test', title: 'Перфекціоніст', description: 'Здати тест на 100%', objective: { action: 'perfect_test', count: 1 }, reward: { gold: 300, crystals: 10 }, diamondReward: 2, icon: '💯' },

  // ─── Соціальне ───
  { id: 'ach_survey', title: 'Відвертий', description: 'Пройти психологічне опитування', objective: { action: 'complete_survey', count: 1 }, reward: { gold: 50 }, diamondReward: 1, icon: '💬' },
  { id: 'ach_hero_lvl_6', title: 'Максимальна еволюція', description: 'Досягти 6 рівня героя', objective: { action: 'hero_level', targetLevel: 6, count: 1 }, reward: { gold: 1000 }, diamondReward: 5, icon: '⭐' },
]

// ─── Підписки ────────────────────────────────────────────────

// Активні місії гравця
export function subscribePlayerMissions(playerId, callback) {
  const q = query(
    collection(db, 'playerMissions'),
    where('playerId', '==', playerId)
  )
  return onSnapshot(q, (snap) => {
    const missions = snap.docs
      .map(d => ({ id: d.id, ...d.data() }))
      .sort((a, b) => (a.order || 0) - (b.order || 0))
    callback(missions)
  })
}

// ─── Ініціалізація місій для нового гравця ───────────────────

export async function initPlayerMissions(playerId) {
  const batch = writeBatch(db)

  // Вибираємо 3 рандомні щоденні місії
  const shuffledDaily = [...DEFAULT_DAILY_MISSIONS].sort(() => Math.random() - 0.5)
  const todayDailies = shuffledDaily.slice(0, 3)

  for (const mission of todayDailies) {
    const ref = doc(collection(db, 'playerMissions'))
    batch.set(ref, {
      playerId,
      missionId: mission.id,
      title: mission.title,
      description: mission.description,
      flavorText: mission.flavorText || '',
      type: 'daily',
      objective: mission.objective,
      reward: mission.reward,
      xpReward: mission.xpReward || 0,
      diamondReward: mission.diamondReward || 0,
      rpReward: mission.rpReward || 0,
      progress: 0,
      target: mission.objective.count,
      status: 'active',    // active | completed | claimed
      expiresAt: getEndOfDay(),
      createdAt: new Date(),
    })
  }

  // Вибираємо 2 рандомні тижневі місії
  const shuffledWeekly = [...DEFAULT_WEEKLY_MISSIONS].sort(() => Math.random() - 0.5)
  const weeklyMissions = shuffledWeekly.slice(0, 2)

  for (const mission of weeklyMissions) {
    const ref = doc(collection(db, 'playerMissions'))
    batch.set(ref, {
      playerId,
      missionId: mission.id,
      title: mission.title,
      description: mission.description,
      type: 'weekly',
      objective: mission.objective,
      reward: mission.reward,
      xpReward: mission.xpReward || 0,
      diamondReward: mission.diamondReward || 0,
      rpReward: mission.rpReward || 0,
      progress: 0,
      target: mission.objective.count,
      status: 'active',
      expiresAt: getEndOfWeek(),
      createdAt: new Date(),
    })
  }

  // Перша сюжетна місія
  const firstStory = DEFAULT_STORY_MISSIONS[0]
  const storyRef = doc(collection(db, 'playerMissions'))
  batch.set(storyRef, {
    playerId,
    missionId: firstStory.id,
    title: firstStory.title,
    description: firstStory.description,
    type: 'story',
    chapter: firstStory.chapter,
    order: firstStory.order,
    objective: firstStory.objective,
    reward: firstStory.reward,
    xpReward: firstStory.xpReward || 0,
    diamondReward: firstStory.diamondReward || 0,
    loreText: firstStory.loreText || '',
    nextMission: firstStory.nextMission || null,
    progress: 0,
    target: firstStory.objective.count,
    status: 'active',
    expiresAt: null, // сюжетні не закінчуються
    createdAt: new Date(),
  })

  // Всі досягнення
  for (const ach of DEFAULT_ACHIEVEMENTS) {
    const ref = doc(collection(db, 'playerMissions'))
    batch.set(ref, {
      playerId,
      missionId: ach.id,
      title: ach.title,
      description: ach.description,
      type: 'achievement',
      icon: ach.icon,
      objective: ach.objective,
      reward: ach.reward || {},
      xpReward: 0,
      diamondReward: ach.diamondReward || 0,
      progress: 0,
      target: ach.objective.count,
      status: 'active',
      expiresAt: null,
      createdAt: new Date(),
    })
  }

  await batch.commit()
}

// ─── Оновлення прогресу місій ────────────────────────────────

/**
 * Викликається після кожної ігрової дії.
 * action: 'collect_mine' | 'upgrade_building' | 'complete_task' | 'trade' | ...
 * details: { target, tier, amount, ... }
 */
export async function updateMissionProgress(playerId, action, details = {}) {
  const q = query(
    collection(db, 'playerMissions'),
    where('playerId', '==', playerId),
    where('status', '==', 'active')
  )
  const snap = await getDocs(q)

  const batch = writeBatch(db)
  let updated = 0

  for (const docSnap of snap.docs) {
    const mission = docSnap.data()
    const obj = mission.objective

    // Перевірка чи дія відповідає місії
    if (obj.action !== action) continue

    // Перевірка target (конкретна будівля / тір руїни)
    if (obj.target) {
      if (Array.isArray(obj.target)) {
        if (!obj.target.includes(details.target)) continue
      } else if (obj.target !== details.target) continue
    }
    if (obj.tier && obj.tier !== details.tier) continue
    if (obj.targetLevel && (details.level || 0) < obj.targetLevel) continue

    // Оновлюємо прогрес
    const increment = details.amount || 1
    const newProgress = Math.min((mission.progress || 0) + increment, mission.target)
    const isComplete = newProgress >= mission.target

    batch.update(docSnap.ref, {
      progress: newProgress,
      ...(isComplete ? { status: 'completed', completedAt: new Date() } : {}),
    })
    updated++
  }

  if (updated > 0) await batch.commit()
  return updated
}

// ─── Забрати нагороду за місію ───────────────────────────────

export async function claimMissionReward(playerId, missionDocId) {
  await runTransaction(db, async (tx) => {
    const missionRef = doc(db, 'playerMissions', missionDocId)
    const missionSnap = await tx.get(missionRef)
    if (!missionSnap.exists()) throw new Error('Місія не знайдена')

    const mission = missionSnap.data()
    if (mission.playerId !== playerId) throw new Error('Не ваша місія')
    if (mission.status !== 'completed') throw new Error('Місія ще не виконана')

    const playerRef = doc(db, 'players', playerId)
    const playerSnap = await tx.get(playerRef)
    if (!playerSnap.exists()) throw new Error('Гравець не знайдений')

    const player = playerSnap.data()
    const updates = { lastActive: serverTimestamp() }

    // Ресурси
    for (const [res, amount] of Object.entries(mission.reward || {})) {
      updates[`resources.${res}`] = (player.resources?.[res] || 0) + amount
    }

    // XP
    if (mission.xpReward) {
      updates.heroXP = (player.heroXP || 0) + mission.xpReward
    }

    // Diamonds
    if (mission.diamondReward) {
      updates.diamonds = (player.diamonds || 0) + mission.diamondReward
    }

    tx.update(playerRef, updates)
    tx.update(missionRef, { status: 'claimed', claimedAt: new Date() })

    // RP (Research Points) — окремо після транзакції (updateDoc)
    if (mission.rpReward) {
      await addResearchPoints(playerId, mission.rpReward)
    }

    // Якщо сюжетна місія — розблокувати наступну
    if (mission.type === 'story' && mission.nextMission) {
      const nextMission = DEFAULT_STORY_MISSIONS.find(m => m.id === mission.nextMission)
      if (nextMission) {
        const nextRef = doc(collection(db, 'playerMissions'))
        tx.set(nextRef, {
          playerId,
          missionId: nextMission.id,
          title: nextMission.title,
          description: nextMission.description,
          type: 'story',
          chapter: nextMission.chapter,
          order: nextMission.order,
          objective: nextMission.objective,
          reward: nextMission.reward,
          xpReward: nextMission.xpReward || 0,
          diamondReward: nextMission.diamondReward || 0,
          loreText: nextMission.loreText || '',
          nextMission: nextMission.nextMission || null,
          progress: 0,
          target: nextMission.objective.count,
          status: 'active',
          expiresAt: null,
          createdAt: new Date(),
        })
      }
    }
  })
}

// ─── Ротація щоденних/тижневих місій ─────────────────────────

export async function rotateDailyMissions(playerId) {
  // Видаляємо старі щоденні (expired)
  const q = query(
    collection(db, 'playerMissions'),
    where('playerId', '==', playerId),
    where('type', '==', 'daily')
  )
  const snap = await getDocs(q)
  const batch = writeBatch(db)

  for (const d of snap.docs) {
    const data = d.data()
    const expires = data.expiresAt?.toDate?.() || new Date(data.expiresAt)
    if (Date.now() > expires.getTime()) {
      batch.delete(d.ref)
    }
  }

  // Додаємо нові 3 щоденні
  const shuffled = [...DEFAULT_DAILY_MISSIONS].sort(() => Math.random() - 0.5)
  for (const mission of shuffled.slice(0, 3)) {
    const ref = doc(collection(db, 'playerMissions'))
    batch.set(ref, {
      playerId,
      missionId: mission.id,
      title: mission.title,
      description: mission.description,
      flavorText: mission.flavorText || '',
      type: 'daily',
      objective: mission.objective,
      reward: mission.reward,
      xpReward: mission.xpReward || 0,
      diamondReward: mission.diamondReward || 0,
      rpReward: mission.rpReward || 0,
      progress: 0,
      target: mission.objective.count,
      status: 'active',
      expiresAt: getEndOfDay(),
      createdAt: new Date(),
    })
  }

  await batch.commit()
}

// ─── Утиліти ─────────────────────────────────────────────────

function getEndOfDay() {
  const d = new Date()
  d.setHours(23, 59, 59, 999)
  return d
}

function getEndOfWeek() {
  const d = new Date()
  const daysUntilSunday = 7 - d.getDay()
  d.setDate(d.getDate() + daysUntilSunday)
  d.setHours(23, 59, 59, 999)
  return d
}
